<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Cake.Bridge.DependencyInjection" Version="2026.7.15.722" />
    <PackageVersion Include="Cake.Common" Version="6.2.0" />
    <PackageVersion Include="Cake.Testing" Version="6.2.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Dapper.AOT" Version="1.0.52" />
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Devlead.Console" Version="2026.7.15.820" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NSubstitute" Version="6.1.0" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Spectre.Console.Testing" Version="0.57.2" />
    <PackageVersion Include="TUnit" Version="1.64.6" />
    <PackageVersion Include="Verify.TUnit" Version="31.28.0" />
  </ItemGroup>
</Project>
